const services = [
  "Waste disposal company",
  "Windows and doors",
  "Foils and labels",
  "Gardening",
  "Scaffolder",
  "Plasterer",
  "Glazier",
  "Heating installer",
  "Insulation company",
  "Refrigeration and air conditioning technology",
  "Chimney sweep",
  "Exterminator",
  "Painter",
  "Bricklayer",
  "Motorcycle workshop",
  "Dumpster service",
  "Stove and fireplace construction",
  "Paver",
  "Planning and advice",
  "Platelayer",
  "Upholstery",
  "Cleaning company",
  "Sanitary",
  "Saddlery",
  "Locksmith",
  "Carpentry",
  "Security technology",
  "Solar engineer",
  "Plumbing",
  "Blinds and roller shutters",
  "Upholsterer",
  "Transport company",
  "Moving company",
  "Fences and gates",
  "Carpentry",
];

export default services;
