const services = [
  "Entsorgungsunternehmen",
  "Fenster und Türen",
  "Folien und Etiketten",
  "Gartenbau",
  "Gerüstbauer",
  "Stuckateur",
  "Glaser",
  "Heizungsinstallateur",
  "Dämmerei",
  "Kälte- und Klimatechnik",
  "Schornsteinfeger",
  "Kammerjäger",
  "Maler",
  "Maurer",
  "Motorradwerkstatt",
  "Müllentsorgung",
  "Ofen- und Kaminbau",
  "Pflasterer",
  "Planung und Beratung",
  "Plattenleger",
  "Polsterung",
  "Reinigungsunternehmen",
  "Sattlerei",
  "Schlosser",
  "Zimmerei",
  "Sicherheitstechnik",
  "Solarinstallateur",
  "Sanitär",
  "Jalousien und Rollläden",
  "Polsterer",
  "Transportunternehmen",
  "Umzugsunternehmen",
  "Zäune und Tore",
];

export default services;
